---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-${{values.name}}
  name: svc-${{values.name}}
spec:
  ports:
  - name: HTTP
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${{values.name}}
  type: ClusterIP
