apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}
  namespace: argocd
spec:
  destination:
    namespace: ${{values.name}}
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://github.com/moquintanilha/${{values.name}}.git
    targetRevision: master
    path: ${{values.name}}
  syncPolicy:
    syncOptions:
      CreateNamespace=true